GPU_QUEUE = "gpu"
CPU_QUEUE = "cpu"

TASK_TRAINING = "model_training"
TASK_INSPECTION = "inspection_run"

STATUS_PENDING = "pending"
STATUS_QUEUED = "queued"
STATUS_RUNNING = "running"
STATUS_PAUSING = "pausing"
STATUS_PAUSED = "paused"
STATUS_RESUMING = "resuming"
STATUS_SUCCEEDED = "succeeded"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"

ACTIVE_STATUSES = {
    STATUS_PENDING,
    STATUS_QUEUED,
    STATUS_RUNNING,
    STATUS_PAUSING,
    STATUS_RESUMING,
}

TERMINAL_STATUSES = {
    STATUS_SUCCEEDED,
    STATUS_FAILED,
    STATUS_CANCELLED,
}

PRIORITY_TRAINING = 40
PRIORITY_TRAINING_RESUME = 60
PRIORITY_INSPECTION = 100
